apiVersion: v1
kind: PersistentVolume
metadata:
  name: historia-api-pv
  labels:
    app: historia-usuario-api
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "1Gi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/koncilia/outputs
    type: DirectoryOrCreate
