apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    app: historia-usuario-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" }}
  storageClassName: "" # Vacío para que busque volúmenes manuales
  volumeName: historia-api-pv
